# Generated by Django 4.2.23 on 2025-06-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_category_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
    ]
